//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvEntitiesDynamicPRO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbEntityCVEntities : DbContext
    {
        public DbEntityCVEntities()
            : base("name=DbEntityCVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLADRE> TBLADRES { get; set; }
        public virtual DbSet<TBLCALISMALARIM> TBLCALISMALARIMs { get; set; }
        public virtual DbSet<TBLHAKKIMDA> TBLHAKKIMDAs { get; set; }
        public virtual DbSet<TBLILETISIM> TBLILETISIMs { get; set; }
        public virtual DbSet<TBLYETENEKLER> TBLYETENEKLERs { get; set; }
        public virtual DbSet<TBLADMIN> TBLADMINs { get; set; }
    }
}
